[package]
name = "geopattern"
version = "0.4.0"
authors = ["Suyash <hi@suy.io>"]
edition = "2018"

[dependencies]
svg = "0.8.0"

[dev-dependencies]
anyhow = "1.0.31"
sha-1 = "0.9.1"
criterion = "0.3.3"

[[bench]]
name = "benches"
harness = false
